branch-defaults:
  main:
    environment: Dockerreacttestproj-env
environment-defaults:
  Dockerreacttestproj-env:
    branch: null
    repository: null
global:
  application_name: docker-react-test-proj
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
